# Perform full build-test-deploy process for the JenkinsBot

name: "JenkinsBot-Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: bootJar
      - name: Collect Project version
        run: |
          ./gradlew properties -q | grep "version:" | awk '{print $2}' | xargs -n1 -I{} echo "project_version="{}  >> $GITHUB_ENV
      - name: Generate changelog - snapshot
        run: |
          clog=$(sed -n '/## ${{ env.project_version }}/,/##/{s/^##.*//;p;}' CHANGELOG.md)
          echo "$clog"
          echo "project_changelog=\"$clog\"" >> $GITHUB_ENV
      - name: Verify changelog - snapshot
        run: |
          echo "### Things that changed in this release"
          echo "${{ env.project_changelog }}"
  coverage:
    needs: build
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: test
      - name: Upload JaCoCo coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
      - name: Upload Unit Tests result
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: junit-report
          path: build/reports/tests/test
      - uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          name: codecov

  deploy:
    name: Deployment
    needs: coverage
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Collect Project version
        run: |
          ./gradlew properties -q | grep "version:" | awk '{print $2}' | xargs -n1 -I{} echo "project_version="{}  >> $GITHUB_ENV
      - name: Spring Boot jar
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: bootJar
      - name: "Trace: Output env"
        run: |
          echo ${{ env.project_version }}

      - if: "!contains(env.project_version, '-SNAPSHOT')"
        run: |
          echo 'Release version processing'

      - name: Docker Build and push version and latest
        if: "!contains(env.project_version, '-SNAPSHOT')"
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: davs87/jenkinsbot:latest,davs87/jenkinsbot:${{ env.project_version }}
          context: .

# TODO: verify me first
      - name: Generate changelog
        if: "!contains(env.project_version, '-SNAPSHOT')"
        run: |
          clog=$(sed "/^## $1$/,/^## ${{ env.project_version }}/!d;//d;/^$/d" CHANGELOG.md)
          echo "$clog"
          echo "project_changelog=$clog" >> $GITHUB_ENV
      - name: Release
        if: "!contains(env.project_version, '-SNAPSHOT')"
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/jenkinsBot-${{ env.project_version }}.jar
          body: |
            New version is available: ${{ env.project_version }}

            ### Things that changed in this release
            ${{ env.project_changelog }}
          draft: false
          prerelease: false
          tag_name: ${{ env.project_version }}
          name: ${{ env.project_version }}

      - if: contains(env.project_version, '-SNAPSHOT')
        run: |
          echo 'SNAPSHOT version processing'
      - name: Docker Build and push latest
        if: "contains(env.project_version, '-SNAPSHOT')"
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: davs87/jenkinsbot:latest
          context: .