name: "JenkinsBot-CodeQuality"

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ master ]

jobs:
  pmd:
    name: PMD Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          sourcePath: 'src'
          rulesets: '${{ github.workspace }}/src/main/resources/pmd/jenkinsbot.xml'
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pmd-report.sarif"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          sarif_file: pmd-report.sarif