# On push to master - perform full build with docker updates

name: JenkinsBot-Deploy

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ['JenkinsBot-Build']
    types:
      - completed
jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: release

# TODO: push to docker:latest
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          tags: davs87/jenkinsbot:latest
#          context: "{{defaultContext}}:mysubdir"

# TODO: depends on testing phase

# TODO: push davs87/jenkinsbot:0.x.x if no SNAPSHOT

# TODO: publish artifact .. on new version
#      - name: Upload output file
#        uses: actions/upload-artifact@v3
#        with:
#          name: output-log-file
#          path: output.log


# TODO: exchange artifact
#  - name: Download a single artifact
#      uses: actions/download-artifact@v3
#      with:
#        name: output-log-file

# TODO: depednds on build
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

#