# On push to master - perform full build with docker updates

name: JenkinsBot

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: release

# TODO: depends on testing phase
# TODO: publish artifact .. on new version
#      - name: Upload output file
#        uses: actions/upload-artifact@v3
#        with:
#          name: output-log-file
#          path: output.log


# TODO: exchange artifact
#  - name: Download a single artifact
#      uses: actions/download-artifact@v3
#      with:
#        name: output-log-file