# On push to master - perform full build with docker updates

name: JenkinsBot-Publish

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["JenkinsBot-Build"]
    types:
      - completed

jobs:

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Collect Project version
        run: |
          ./gradlew properties -q | grep "version:" | awk '{print $2}' | xargs -n1 -I{} echo "project_version="{}  >> $GITHUB_ENV
      - name: Spring Boot jar
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: bootJar
      - name: "Trace: Output env"
        run: |
          echo ${{ env.project_version }}

      - if: "!contains(env.project_version, '-SNAPSHOT')"
        run: |
          echo 'Release version processing'

# TODO: use composite action (?)
      - name: Build with Gradle
        if: "!contains(env.project_version, '-SNAPSHOT')"
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: release
      - name: Generate changelog
        if: "!contains(env.project_version, '-SNAPSHOT')"
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: "!contains(env.project_version, '-SNAPSHOT')"
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/jenkinsBot-${{ env.project_version }}.jar
          body: |
            New version is available: ${{ env.project_version }}

            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          tag_name: ${{ env.project_version }}
          name: ${{ env.project_version }}
# TODO: docker push :env.project_version

      - if: contains(env.project_version, '-SNAPSHOT')
        run: |
          echo 'SNAPSHOT version processing'
# TODO: docker push :latest


# TODO: push to docker:latest; push davs87/jenkinsbot:0.x.x if no SNAPSHOT
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          tags: davs87/jenkinsbot:latest
#          context: "{{defaultContext}}:mysubdir"

# TODO: exchange artifact
#      - name: Upload output file
#        uses: actions/upload-artifact@v3
#        with:
#          name: output-log-file
#          path: output.log

#  - name: Download a single artifact
#      uses: actions/download-artifact@v3
#      with:
#        name: output-log-file