# On pull-request - perform build with unit tests

name: JenkinsBot - PullRequest handler

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          password: ${{ secrets.TOKEN }}
      - name: Archive Jacoco reports
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-reports
          path: "build/reports/jacoco/test/jacocoTestReport.xml"